=== and146/SPLAT-ARI/jsky/src/main/resources/AstroCat.dtd
<!--

This DTD describes the format of an XML catalog server description file.
  
There are two types of XML files that use this DTD:

  1: A top level catalog directory file (see conf/AstroCat.xml), which
     lists only the names and types of catalogs that are defined
     elsewhere. 

  2: A catalog description file that describes the query parameters for a
     single catalog.  In this case, the XML file describes the CGI-BIN
     parameters and the catalog server URL. 
     
In the first case, the XML file contains a list of catalogs. The
"path" attribute of a catalog element can point to another XML file
describing the catalog server in more detail, or the "class" attribute
can point to a Java class that implements a catalog directory.  If no
path or class attributes are given, the catalog is expected be defined
elsewhere (for example, in the skycat.cfg file). Such entries are
included in the AstroCat.xml file, so that they appear in the catalog
menu in the user interface. Only catalogs in the top level directory
appear in the menu. The others are only accessible via the catalog
tree widget.
  
Plot symbol descriptions may be included in either type of XML file.
When you edit the plot symbol descriptions in the user interface, they
are saved in the ~/.jsky/AstroCat.xml file and override the
descriptions in the detailed XML files.


  $Id: AstroCat.dtd,v 1.2 2002/08/20 09:57:57 brighton Exp $
-->


<!-- The ASTROCAT_DTD_VERSION is updated whenever the structure or content
     of the DTD is altered.
-->
<!ENTITY ASTROCAT_DTD_VERSION "0.1">


<!-- catalogs is the top level element and contains a list of catalog elements.

     The root element is required to have a version attribute set to
     the value of the DTD used in the document.
-->
<!ELEMENT catalogs (catalog)+>
<!ATTLIST catalogs
          version   CDATA #FIXED "&ASTROCAT_DTD_VERSION;"
>


<!-- A catalog element describes one HTTP based catalog server

     Attributes:

     id                a short identifier for the catalog

     name              the display name of the catalog

     description       a short description of the catalog (also used for copyright notice)

     docURL            a URL pointing to documentation for the catalog

     type              identifies the type of the catalog 
                       (one of "catalog", "archive", "imagesvr", "directory", "namesvr", ...)

     protocol          "http" for remote server (default), "file" for local catalog command

     host              the host name for HTTP access

     port              the port number for HTTP access (default: 80)

     path              the path for HTTP access, without parameters

     class             If the type attribute is set to "directory", and the path attribute is not set, 
                       this should be the path name of a Java class that implements the method  
		       "public static CatalogDirectory getDirectory()", which returns a catalog directory 
		       by searching the default locations. 
                       
-->
<!ELEMENT catalog (params?, symbols?)>
<!ATTLIST catalog
          id               CDATA #IMPLIED
          name             CDATA #REQUIRED
          description      CDATA #IMPLIED
          docURL           CDATA #IMPLIED
          type             CDATA #REQUIRED
          protocol         CDATA #IMPLIED
          host             CDATA #IMPLIED
          port             CDATA #IMPLIED
          path             CDATA #REQUIRED
          class            CDATA #IMPLIED
>


<!-- params contains a list of param elements describing the catalog's query parameters.
-->
<!ELEMENT params (param)+>


<!-- A param element describes one catalog server parameter

     Attributes:

     id                the parameter name used in the URL or command line

     name              the display name of the parameter

     description       a short description of the parameter

     value             the default value of the parameter

     (The following attributes are needed for center position and radius related parameters)

     type              the parameter type (used to identify key parameters for cone search)
                       for example: "ra", "dec", "radec", "radius", "equinox", "epoch". 
		       May also be "hidden", if the parameter should be included in the URL, but 
		       not displayed (in which case the "value" attribute should be defined).

     units             units of the parameter: for example: "arcmin", "arcsec", "deg", "hours"

     format            the format that the server expects the parameter in 
                       for example: "h:m:s", "d:m:s", "h m s", "d m s", "hours", "deg"
-->
<!ELEMENT param (options)?>
<!ATTLIST param
          id               CDATA #REQUIRED
          name             CDATA #REQUIRED
          description      CDATA #REQUIRED
          value            CDATA #IMPLIED
          type             CDATA #IMPLIED
          units            CDATA #IMPLIED
          format           CDATA #IMPLIED
>



<!-- options contains a list of option elements describing a parameter's possible values
-->
<!ELEMENT options (option)+>


<!-- An option element describes one of the possible parameter values

     Attributes:

     name              the display name of this option

     value             the value to use for this option
-->
<!ELEMENT option EMPTY>
<!ATTLIST option
          name             CDATA #REQUIRED
          value            CDATA #REQUIRED
>



<!-- symbols contains a list of plot symbol definitions that describe how to plot rows in
     a table returned from this catalog as an image overlay. 
-->
<!ELEMENT symbols (symbol)+>


<!-- A symbol element describes how to plot a row in a table returned from a query to this
     catalog. 

     Attributes:

     name            a name to display for this symbol definition in a property editor

     description     an optional description of this plot symbol definition

     raCol           Optional index of the center position RA column (default 1)

     decCol          Optional index of the center position Dec column (default 2)

     equinox         Optional equinox of RA and DEC (default J2000)

     columnsUsed     a space separated list of column names that are used as variables in expressions 
                     (default: none).

     shape           the shape of the plot symbol: one of :"circle", "square", "plus",
	             "cross", "triangle", "diamond", "ellipse", "compass", "line", "arrow"
		     (default: "circle")

     color           the symbol's color: one of: "black", "blue", "cyan", "darkGray","gray", 
	             "green", "lightGray", "magenta", "orange", "pink", "red",  "white", "yellow"
		     (default: "white")

     The following five attributes may all be expressions in Java syntax using column names as variables.

     condition       the symbol is only drawn if the condition evaluates to true (default: true)

     ratio           the x/y ratio (ellipticity ratio) of the symbol (default: 1)

     angle           the rotation angle, from WCS north, in degrees (default: 0)

     label           a text label to display next to the symbol (default: no label)

     size            the size (radius) of the symbol in the given units (default: 5 pixels)


     units           the units of the symbol size: one of: "deg" (WCS degrees),
                     "image" (image pixels, default)
-->
<!ELEMENT symbol EMPTY>
<!ATTLIST symbol
          name           CDATA #REQUIRED
          description    CDATA #IMPLIED
          raCol          CDATA #IMPLIED
          decCol         CDATA #IMPLIED
          equinox        CDATA #IMPLIED
          columnsUsed    CDATA #IMPLIED
          shape          CDATA #IMPLIED
          color          CDATA #IMPLIED
          condition      CDATA #IMPLIED
          ratio          CDATA #IMPLIED
          angle          CDATA #IMPLIED
          label          CDATA #IMPLIED
          size           CDATA #IMPLIED
          units          CDATA #IMPLIED>

=== and146/SPLAT-ARI/jsky/src/main/resources/conf/ISSAImg.xml
<?xml version="1.0"?>
<!DOCTYPE catalog PUBLIC "-//JSky//DTD for Catalog Access//EN" "AstroCat.dtd">
<!--
  This document describes the query arguments and access method for an astronomical catalog.
-->


 <catalog 
   id="ISSAImg@OASIS" 
   name="ISSA Image Service" 
   description="Accessed via the NASA/IPAC Infrared Science Archive"
   type="imagesvr"
   protocol="http"
   host="irsa.ipac.caltech.edu"
   path="/cgi-bin/Oasis/ISSAImg/nph-issaimg">
   <params>
     <param 
       id="objstr" 
       name="Object or location"
       description="Object name or coordinate string (fairly free-form)."
       type="radec"/>
     <param 
       id="size" 
       name="Size"
       units="deg"
       description="Cropped image size"
       type="size"/>
     <param 
       id="band" 
       name="Band"
       description="2MASS band (J, H, or K)"
       value="12">
       <options>
         <option name="12" value="1"/>
         <option name="25" value="2"/>
	 <option name="60" value="3"/>
	 <option name="100" value="4"/>
       </options>
     </param>
   </params>
 </catalog>

=== and146/SPLAT-ARI/jsky/src/main/resources/conf/2MASSImg.xml
<?xml version="1.0"?>
<!DOCTYPE catalog PUBLIC "-//JSky//DTD for Catalog Access//EN" "AstroCat.dtd">
<!--
  This document describes the query arguments and access method for an astronomical catalog.
-->


 <catalog 
   id="2MASSImg@OASIS" 
   name="2MASS Quick-Look Image Retrieval Service" 
   description="Accessed via the NASA/IPAC Infrared Science Archive"
   type="imagesvr"
   protocol="http"
   host="irsa.ipac.caltech.edu"
   path="/cgi-bin/Oasis/2MASSImg/nph-2massimg">
   <params>
     <param 
       id="objstr" 
       name="Object or location"
       description="Object name or coordinate string (fairly free-form)."
       type="radec"/>
     <param 
       id="size" 
       name="Size"
       units="arcsec"
       description="Cropped image size"
       type="size"/>
     <param 
       id="band" 
       name="Band"
       description="2MASS band (J, H, or K)"
       value="J">
       <options>
         <option name="J" value="J"/>
         <option name="H" value="H"/>
         <option name="K" value="K"/>
       </options>
     </param>
   </params>
 </catalog>

=== and146/SPLAT-ARI/jsky/src/main/resources/conf/AladinDSS1Img.xml
<?xml version="1.0"?>
<!DOCTYPE catalogs PUBLIC "-//JSky//DTD for Catalog Access//EN" "AstroCat.dtd">
<!--
  This document describes the query arguments and access methods for astronomical catalogs.
  A catalog may be implemented as a cgi-bin application, accessed via HTTP,
  as a local command, or as a local file in a known format. 
-->

 <catalog 
   id="aladin@cds" 
   name="POSSI/DSS1 via Aladin Image Server (CDS/Vizier)" 
   description="Origin: NASA/IPAC Infrared Science Archive"
   type="imagesvr"
   protocol="http"
   host="aladin.u-strasbg.fr"
   path="/java/alapre.pl">
   <params>
     <param 
       id="-source" 
       name="Source"
       description="Source Catalog"
       value="POSSI"
       type="hidden"/>
     <param 
       id="-c" 
       name="Center"
       description="Object Name"
       type="radec"
       format="h+m+s d+m+s"/>
     <param 
       id="-c.eq" 
       name="Equinox"
       type="equinox"
       description="Equinox of RA and Dec (default: J2000)"
       value="J2000"/>
     <param 
       id="-c.ep" 
       name="Epoch"
       type="epoch"
       description="Epoch of RA and Dec (default: 2000)"
       value="2000"/>
     <param 
       id="-c.rm" 
       name="Radius"
       type="radius"
       description="Radius from center RA, Dec in arcmin (may be two values: min and max radius)"
       value="15"/>
     <param 
       id="out" 
       name="Output"
       description="Output format"
       value="image"
       type="hidden"/>
     <param 
       id="fmt" 
       name="Format"
       description="Image format"
       value="FITS">
       <options>
         <option name="FITS" value="FITS"/>
         <option name="JPEG" value="JPEG"/>
       </options>
     </param>
     <param 
       id="resolution" 
       name="Resolution"
       description="Resolution"
       value="STAND">
       <options>
         <option name="Full Resolution" value="STAND"/>
         <option name="Low Resolution" value="LOW"/>
         <option name="Plate View" value="PLATE"/>
       </options>
     </param>
     <param 
       id="qual" 
       name="Band"
       description="Image band"
       type="hidden"
       value="POSSI+E+____"/>
       
   </params>
 </catalog>

=== and146/SPLAT-ARI/jsky/src/main/resources/conf/AstroCat.xml
<?xml version="1.0"?>
<!DOCTYPE catalogs PUBLIC "-//JSky//DTD for Catalog Access//EN" "AstroCat.dtd">
<!--

  This document describes the top level catalog directory and lists
  the names and types of the catalogs that will appear in the user
  interface menus. The path attribute of a catalog element points to a
  file containing a detailed description. Catalogs with no path
  attribute refer to catalogs that are defined elsewhere, such as in
  one of the catalog subdirectories (see "Skycat Catalogs", and "IRSA
  Catalogs" below).

-->

<catalogs version="0.1">

<!-- 
  Catalog Subdirectories 
  
  The next two lines describe the Skycat and IRSA catalog directories, and the classes
  that implement them. 
-->
  <catalog name="Skycat Catalogs" type="directory" class="jsky.catalog.skycat.SkycatConfigFile"/>
  <catalog name="IRSA Catalogs"   type="directory" class="jsky.catalog.irsa.IRSAConfig"/>


<!-- The GSC2 catalog at ESO, described in XML (instead of in the skycat.cfg file) 
  <catalog name="Guide Star Catalog at ESO (v2)" type="catalog" path="gsc2_eso.xml"/>
-->

<!-- Include references to some of the Skycat catalogs (Should be defined in the skycat.cfg file) -->

  <catalog name="2MASS Catalog at CDS"/>
  <catalog name="ABELL at CADC"/>
  <catalog name="GSC-2 at ESO"/>
  <catalog name="GSC-2 at STScI"/>
  <catalog name="Guide Star Catalog at CADC"/>
  <catalog name="Guide Star Catalog at ESO"/>
  <catalog name="USNO at CADC"/>
  <catalog name="USNO at ESO"/>
  <catalog name="QSO at CADC"/>
  <catalog name="RC3 at CADC"/>
  <catalog name="SAO at CADC"/>
  <catalog name="IRAS at CADC"/>
  <catalog name="PPM at ESO"/>
  <catalog name="SIMBAD via ESO"/>
  <catalog name="ZCAT at CADC"/>
  <catalog name="NED at ESO"/>

<!-- Skycat Archives (should be defined in the skycat.cfg file) -->

  <catalog name="CFHT Archive at CADC"/>
  <catalog name="HST Archive at CADC"/>
  <catalog name="NTT Archive at ESO"/>

<!-- Skycat Image Servers (should be defined in the skycat.cfg file) -->
  <catalog name="Digitized Sky at CADC (2nd Generation)"/>
  <catalog name="Digitized Sky at CADC"/>
  <catalog name="Digitized Sky at ESO"/>


<!-- IRSA Catalogs (defined in the IRSA config file, nph-catlist.xml)

  <catalog name="2MASS Second Incremental Release Point Source Catalog (PSC)"/>
  <catalog name="USNOA-2"/>
  <catalog name="The ROSAT Bright Sources"/>
  <catalog name="The ROSAT Faint Sources"/>
-->

<!-- IRSA Image Servers -->
  <catalog name="2MASS Quick-Look Image Retrieval Service" type="imagesvr" path="2MASSImg.xml"/>

<!-- (These still need testing)
  <catalog name="ISSA Image Service" type="imagesvr" path="ISSAImg.xml"/>
  <catalog name="IRAS Galaxy Atlas Image Service" type="imagesvr" path="IRASImg.xml"/>
  <catalog name="MSX Image Service" type="imagesvr" path="MSXImg.xml"/>
-->

<!-- Aladin Image Servers -->
<!-- (Still needs testing)
  <catalog name="2MASS via Aladin Image Server (CDS/Vizier)" type="imagesvr" path="Aladin2MASSImg.xml"/>
  <catalog name="POSSI/DSS1 via Aladin Image Server (CDS/Vizier)" type="imagesvr" path="AladinDSS1Img.xml"/>
  <catalog name="POSSII/DSS2 via Aladin Image Server (CDS/Vizier)" type="imagesvr" path="AladinDSS2Img.xml"/>
-->

</catalogs>

=== and146/SPLAT-ARI/jsky/src/main/resources/conf/gsc_eso.xml
<?xml version="1.0"?>
<!DOCTYPE catalogs PUBLIC "-//JSky//DTD for Catalog Access//EN" "AstroCat.dtd">
<!--
  This document describes the query arguments and access method for an astronomical catalog.

  XXX Work in progress XXX
-->

<catalogs version="0.1">
 <catalog 
   id="gsc@eso" 
   name="Guide Star Catalog at ESO (v1)" 
   type="catalog"
   protocol="http"
   host="archive.eso.org"
   path="/skycat/servers/gsc-server">

   <params>
     <param 
       id="center" 
       name="Center (RA Dec)"
       description="Center RA, Dec Coordinates in J2000"
       type="radec"/>
     <param 
       id="radius" 
       name="Radius"
       description="Radius from center RA, Dec in arcmin (may be two values: min, max radius)"
       type="radius"
       units="arcmin"/>
     <param 
       id="mag" 
       name="Mag"
       description="Magnitude (may be two values: min, max magnitude)"
       value="0,15"/>
     <param 
       id="nout" 
       name="Max Rows"
       description="Maximum number of rows to return"
       value="1000"/>
     <param 
       id="sort" 
       name="Sort"
       description="Sort order for results"
       value="d'"/>
     <param 
       id="format" 
       name="Format"
       description="Output format"
       value="8"
       type="hidden"/>
   </params>

   <symbols version="0.1">
     <symbol 
       name="Magnitude"
       description="Show symbol positions and magnitudes"
       raCol="1"
       decCol="2"
       equinox="J2000"
       columsUsed="mag"
       shape="square"
       color="white"
       condition="1"
       ratio="1"
       angle="0"
       label=""
       size="(25-mag)/3600."
       units="deg"/>
   </symbols>

 </catalog>
</catalogs>

=== and146/SPLAT-ARI/jsky/src/main/resources/conf/gsc2_eso.xml
<?xml version="1.0"?>
<!DOCTYPE catalogs PUBLIC "-//JSky//DTD for Catalog Access//EN" "AstroCat.dtd">
<!--
  This document describes the query arguments and access method for an astronomical catalog.
-->

<catalogs version="0.1">
 <catalog 
   id="gsc@eso" 
   name="Guide Star Catalog at ESO (v2)" 
   type="catalog"
   protocol="http"
   host="archive.eso.org"
   port="80"
   path="/skycat/servers/gsc2query">

   <params>
     <param 
       id="ra" 
       name="RA"
       description="Center RA Coordinate in J2000"
       type="ra"/>
     <param 
       id="dec" 
       name="Dec"
       description="Center Dec Coordinate in J2000"
       type="dec"/>
     <param 
       id="r1" 
       name="Min Radius"
       description="Inner (default is 0.0) seach radius (arcmin)"
       type="minRadius"
       units="arcmin"/>
     <param 
       id="r2" 
       name="Max Radius"
       description="Outer seach radius (arcmin)"
       type="maxRadius"
       units="arcmin"/>
     <param 
       id="m1" 
       name="Brightest (min)"
       description="optional magnitude limit [bright] default: 0"/>
     <param 
       id="m2" 
       name="Faintest (max)"
       description="optional magnitude limit [faint] default: 30"/>
     <param 
       id="n" 
       name="Max Rows"
       type="maxrows"
       description="Maximum number of rows to return"/>
   </params>

   <symbols>
      <symbol 
        columnsUsed="Fmag" 
	shape="square" 
	color="white"  
	condition="Fmag &gt; 0." 
	ratio="1" 
	angle="0" 
	label="" 
	size="(23-Fmag)/18000." 
	units="deg"/>
      <symbol 
        columnsUsed="Fmag Vmag Jmag" 
	shape="square" color="yellow" 
	condition="Fmag &lt; 0. &amp;&amp; Jmag &gt; 0" 
	ratio="1" 
	angle="0" 
	label="" 
	size="(23-Jmag)/18000." 
	units="deg 2000"/>
      <symbol 
        columnsUsed="Fmag Vmag Jmag" 
	shape="square" 
	color="green" 
	condition="Fmag &lt; 0. &amp;&amp; Jmag &lt; 0. &amp;&amp; Vmag &gt; 0." 
	ratio="1" 
	angle="0" 
	label="" 
	size="(23-Vmag)/18000." 
	units="deg 2000"/>
   </symbols>

 </catalog>
</catalogs>

=== and146/SPLAT-ARI/jsky/src/main/resources/conf/MSXImg.xml
<?xml version="1.0"?>
<!DOCTYPE catalog PUBLIC "-//JSky//DTD for Catalog Access//EN" "AstroCat.dtd">
<!--
  This document describes the query arguments and access method for an astronomical catalog.
-->


 <catalog 
   id="MSXImg@OASIS" 
   name="MSX Image Service" 
   description="Accessed via the NASA/IPAC Infrared Science Archive"
   type="imagesvr"
   protocol="http"
   host="irsa.ipac.caltech.edu"
   path="/cgi-bin/Oasis/MSXImg/nph-msximg">
   <params>
     <param 
       id="objstr" 
       name="Object or location"
       description="Object name or coordinate string (fairly free-form)."
       type="radec"/>
     <param 
       id="size" 
       name="Size"
       units="deg"
       description="Image Size"
       type="size"/>
     <param 
       id="band" 
       name="Band"
       description="MSX band (A, C, D, or E)"
       value="A">
       <options>
         <option name="A" value="3"/>
         <option name="C" value="4"/>
         <option name="D" value="5"/>
         <option name="E" value="6"/>
       </options>
     </param>
   </params>
 </catalog>
